// Mirrored from _scripts/run_ipo_pipeline_lean.py step() calls.
export const EXPECTED_LEAN_STEPS: Array<{ step: string; weekly?: boolean }> = [
  { step: "schema sync (single owner of DDL)" },
  { step: "write-constraint guard (A)" },
  { step: "lineage registry (P2)" },
  { step: "NSE discovery (new IPOs)" },
  { step: "IPOMatrix enrich (new IPOs)" },
  { step: "IPOMatrix refresh (upcoming drip-feed)" },
  { step: "EPS backfill (caution-marked)" },
  { step: "refresh GMP" },
  { step: "delivery pct (NSE bhavcopy)" },
  { step: "market regime + VIX (today)" },
  { step: "candles: in-window daily sync" },
  { step: "listing-day fields (kite)" },
  { step: "derive listing_open" },
  { step: "download SBI notes (new only)" },
  { step: "parse SBI notes -> DB" },
  { step: "street news discovery (free RSS)" },
  { step: "SBI Haiku extract ($0.50 cap)" },
  { step: "RHP forensic (Sonnet, $3/day cap)" },
  { step: "ipo score v0 (derived)" },
  { step: "d10 outcome precompute" },
  { step: "reconcile listing dates" },
  { step: "master computables backfill" },
  { step: "peer PE from SBI notes (fill-empty)" },
  { step: "peer PE (fetch, fair-value input)" },
  { step: "sync issue_details -> intelligence (isin)" },
  { step: "compute IPO verdicts (TRADE/WATCH/CAUTION/AVOID)" },
  { step: "compute red-flag scanner" },
  { step: "Quality score (pre-list)" },
  { step: "sync trade journal (kite orders)" },
  { step: "compute journal outcomes" },
  { step: "backup critical tables" },
  { step: "purge post-lock candles", weekly: true },
  { step: "health-check (gate)" },
  { step: "value-sanity report" },
  { step: "date sanity gate (D)" },
  { step: "freshness monitor (P2)" },
  { step: "smoke probe (live API)" },
];
