import type { IpoData } from "./scoring"

export const IPO_PIPELINE: IpoData[] = [
  // ── CMR GREEN TECHNOLOGIES (SBI Securities note: Jun 2026) ──
  {
    name: "CMR Green Technologies",
    sector: "Metals - Recycling",
    issueSize: 631,
    freshIssuePct: 0,      // 100% OFS
    ofsPct: 100,
    priceBandLow: 182,
    priceBandHigh: 192,
    anchors: ["Goldman Sachs", "BNP Paribas", "Equirus Capital", "ICICI Securities", "Motilal Oswal"],
    retailX: 27,
    niiX: 172,
    qibX: 270,
    totalX: 127,
    revenueCAGR: 6.8,       // FY23→FY25: 5869→6666 = 6.8% CAGR
    patCAGR: 21.5,          // Adj PAT: 105→155 = 21.5% CAGR
    roe: 11.3,              // FY25
    roce: 12.0,             // FY25
    debtEquity: 0.7,        // FY25: 894/1373
    ebitdaMargin: 4.6,      // FY25
    fcfPositive: false,     // FY25 FCF was -330cr
    peRatio: 20.3,          // Annualized 9MFY26 PE
    pbRatio: 3.1,           // FY25
    evEbitda: 12.6,         // FY26 peer basis
    peerPE: 31.7,           // Gravita India (closest peer)
    peerLabel: "Gravita India (31.7x), Pondy Oxides (30.7x)",
    gmpPrice: 70,           // Final GMP Jun 5 (high: ₹77, low: ₹25 on May 30)
    gmpTrend: [25, 30, 38, 52, 55, 70, 77],  // May 30 → Jun 5 actual
    promoterHoldingPostIpo: 84,
    promoterClean: true,
    auditorOk: true,
    noRegulatoryIssues: false,  // goodwill writeoff FY24 is a concern
    relatedPartyTxPct: 3,       // top 3 customers = 20.9% rev (moderate)
    capitalAllocationScore: 52, // growing but FCF negative
    executionTrackRecord: true,
    industryReputation: 60,     // leading recycler but not widely known
    lotSize: 78,
    drhpFiled: true,
    status: "OPEN",
    // 2026 COLD MARKET CONTEXT: avg listing +2.3%, positive rate only 42%
    // 7 of 24 listed in 2026 had negative listing (Powerica -5%, CMPDI -7%, Amagi -12%)
    // BUT: CMR Green QIB 270x is exceptional — strongest signal
    // GMP ₹70 means expected listing ~₹261-₹269 (accounting for cold market discount)
    // SBI Sec recommendation: SUBSCRIBE
    brokerReco: "SUBSCRIBE",
    brokerNote: "Largest recycled aluminium player (4x nearest competitor capacity). P/E 20.3x vs peers at 30-36x = 35% discount. Risk: 100% OFS, FCF negative in FY25, customer concentration (top 3 = 20.9% revenue)",
  },
  // ── NSDL ──
  {
    name: "NSDL",
    sector: "Financial Infrastructure",
    issueSize: 3000,
    freshIssuePct: 80,
    ofsPct: 20,
    priceBandLow: 760,
    priceBandHigh: 800,
    anchors: ["SBI MF", "HDFC MF", "GIC Singapore", "Fidelity", "Mirae Asset"],
    retailX: 12,
    niiX: 43,
    qibX: 187,
    totalX: 113,
    revenueCAGR: 18,
    patCAGR: 22,
    roe: 28,
    roce: 32,
    debtEquity: 0.1,
    ebitdaMargin: 45,
    fcfPositive: true,
    peRatio: 35,
    peerPE: 50,
    peerLabel: "CDSL (50x PE)",
    gmpPrice: 680,
    gmpTrend: [400, 450, 520, 580, 640, 660, 680],
    promoterHoldingPostIpo: 85,
    promoterClean: true,
    auditorOk: true,
    noRegulatoryIssues: true,
    relatedPartyTxPct: 2,
    capitalAllocationScore: 80,
    executionTrackRecord: true,
    industryReputation: 90,
    lotSize: 50,
    drhpFiled: true,
    status: "OPEN",
  },
  // ── GROWW ──
  {
    name: "Groww (Billionloans)",
    sector: "Fintech / Wealth",
    issueSize: 5500,
    freshIssuePct: 60,
    ofsPct: 40,
    priceBandLow: 1200,
    priceBandHigh: 1250,
    anchors: ["BlackRock", "Nomura", "ICICI Prudential MF", "SBI MF"],
    retailX: 9,
    niiX: 38,
    qibX: 143,
    totalX: 89,
    revenueCAGR: 65,
    patCAGR: 120,
    roe: 18,
    roce: 22,
    debtEquity: 0.2,
    ebitdaMargin: 28,
    fcfPositive: true,
    peRatio: 85,
    peerPE: 95,
    peerLabel: "Angel One (95x PE)",
    gmpPrice: 775,
    gmpTrend: [500, 580, 640, 700, 730, 755, 775],
    promoterClean: true,
    auditorOk: true,
    noRegulatoryIssues: true,
    drhpFiled: true,
    status: "UPCOMING",
  },
  // ── URBAN COMPANY ──
  {
    name: "Urban Company",
    sector: "Services Platform",
    issueSize: 2800,
    freshIssuePct: 35,
    ofsPct: 65,
    priceBandLow: 480,
    priceBandHigh: 520,
    anchors: ["Steadview Capital", "Tiger Global"],
    retailX: 5,
    niiX: 18,
    qibX: 67,
    totalX: 35,
    revenueCAGR: 28,
    patCAGR: -5,
    roe: -8,
    roce: -5,
    debtEquity: 0.8,
    ebitdaMargin: 8,
    fcfPositive: false,
    gmpPrice: 145,
    gmpTrend: [80, 95, 110, 125, 135, 140, 145],
    promoterClean: true,
    auditorOk: true,
    noRegulatoryIssues: true,
    drhpFiled: false,
    status: "UPCOMING",
  },
  // ── WAAREE (Listed — for post-listing analysis) ──
  {
    name: "Waaree Energies",
    sector: "Solar Manufacturing",
    issueSize: 4200,
    freshIssuePct: 85,
    ofsPct: 15,
    priceBandLow: 1427,
    priceBandHigh: 1503,
    anchors: ["GIC Singapore", "Fidelity", "SBI MF", "HDFC MF"],
    qibX: 98,
    retailX: 7,
    totalX: 76,
    revenueCAGR: 55,
    patCAGR: 95,
    roe: 32,
    roce: 38,
    debtEquity: 0.3,
    ebitdaMargin: 28,
    fcfPositive: true,
    listingPrice: 2550,
    gmpPrice: 0,
    gmpTrend: [],
    promoterClean: true,
    auditorOk: true,
    noRegulatoryIssues: true,
    drhpFiled: true,
    status: "LISTED",
  },
  // ── OMNITECH ENGINEERING (SBI Securities note: Feb 2026) ──
  {
    name: "Omnitech Engineering Ltd",
    sector: "Precision Manufacturing/Capital Goods",
    issueSize: 583,
    freshIssuePct: 71.7,
    ofsPct: 28.3,
    priceBandLow: 216,
    priceBandHigh: 227,
    lotSize: 66,
    anchors: [],
    revenueCAGR: 39,
    patCAGR: 17,
    roe: 21.5,
    roce: 16.1,
    debtEquity: 1.6,
    ebitdaMargin: 34.3,
    fcfPositive: false,
    peRatio: 64.0,
    peerPE: 60.0,
    peerLabel: "Unimech Aerospace (60x), Azad Engineering (124x)",
    promoterHoldingPostIpo: 74.2,
    promoterClean: true,
    auditorOk: true,
    noRegulatoryIssues: true,
    capitalAllocationScore: 65,
    executionTrackRecord: true,
    industryReputation: 70,
    relatedPartyTxPct: 3,
    status: "LISTED" as const,
    brokerReco: "Subscribe LT",
    brokerNote: "High-growth precision mfg with ₹1,765Cr order book (5.1x FY25 revenue). Rev/EBITDA/PAT CAGR 39/36/17%. D/E reduces 1.6x→0.5x post-issue. PE 64x vs peers 60-124x. Risk: FCF negative, high WC cycle 271 days, 79% export revenue.",
  },
  // ── SEDEMAC MECHATRONICS (SBI Securities note: Mar 2026) ──
  {
    name: "SEDEMAC Mechatronics Ltd",
    sector: "Auto Components/ECU Technology",
    issueSize: 1087,
    freshIssuePct: 0,
    ofsPct: 100,
    priceBandLow: 1287,
    priceBandHigh: 1352,
    lotSize: 11,
    anchors: [],
    revenueCAGR: 34,
    patCAGR: 123,
    roe: 15.5,
    roce: 22.6,
    debtEquity: 0.2,
    ebitdaMargin: 18.4,
    fcfPositive: false,
    peRatio: 62.6,
    peerPE: 63.5,
    peerLabel: "ZF Commercial (64x), Bosch (53x), Sona BLW (57x)",
    promoterHoldingPostIpo: 26.2,
    promoterClean: true,
    auditorOk: true,
    noRegulatoryIssues: true,
    capitalAllocationScore: 80,
    executionTrackRecord: true,
    industryReputation: 85,
    relatedPartyTxPct: 2,
    status: "LISTED" as const,
    brokerReco: "Subscribe LT",
    brokerNote: "35% ISG ECU market share (2W/3W), 75-77% genset controller share. PAT CAGR 123% FY23-FY26E. PE 62.6x, fair vs peers. CRITICAL: 100% OFS — zero fresh capital. TVS Motor = 79% revenue (extreme concentration). Listing gains unlikely per SBI.",
  },
  // ── SAI PARENTERALS (SBI Securities note: Mar 2026) ──
  {
    name: "Sai Parenterals Ltd",
    sector: "Pharma/CDMO",
    issueSize: 409,
    freshIssuePct: 69.7,
    ofsPct: 30.3,
    priceBandLow: 372,
    priceBandHigh: 392,
    lotSize: 38,
    anchors: [],
    revenueCAGR: 30,
    patCAGR: 87,
    roe: 15.4,
    roce: 17.0,
    debtEquity: 1.0,
    ebitdaMargin: 24.1,
    fcfPositive: false,
    peRatio: 88.2,
    peerPE: 125.3,
    peerLabel: "Sai Life Sciences (125x), Senores Pharma (57x)",
    promoterHoldingPostIpo: 51.2,
    promoterClean: true,
    auditorOk: true,
    noRegulatoryIssues: true,
    capitalAllocationScore: 60,
    executionTrackRecord: true,
    industryReputation: 65,
    relatedPartyTxPct: 4,
    status: "LISTED" as const,
    brokerReco: "Subscribe LT",
    brokerNote: "Pharma CDMO + branded generics. Noumed acquisition adds 451 dossiers (huge optionality). PE 88x at discount to Sai Life 125x. Risk: FCF negative FY23/24/1HFY26, cash conversion cycle 311 days, Noumed execution risk.",
  },
]

export function getIpoByName(name: string): IpoData | undefined {
  return IPO_PIPELINE.find(i => i.name.toLowerCase().includes(name.toLowerCase()))
}

export function getIposByStatus(status: "UPCOMING" | "OPEN" | "LISTED"): IpoData[] {
  return IPO_PIPELINE.filter(i => i.status === status)
}
