// workers/ingest/tests/identity.test.ts
//
// Locked identity-normalisation fixtures. These fixtures MUST match the
// output of `pipeline/fill_ipo.py:_norm` and `tools/migrate/neon_to_d1.py:_norm_name`
// verbatim. If any of these assertions ever regress, the Neon→D1 identity
// resolution silently breaks (name-keyed rows in ipo_rhp_intel /
// ipo_research_notes stop landing on the right ipo.id).
//
// The Python side of these fixtures is regenerated by the printout at the
// end of this file's docstring — keep both sides in lockstep.

import test from "node:test";
import assert from "node:assert/strict";
import { normaliseName } from "../src/identity";

// (input, expected) — identical to the Python normaliser output.
const FIXTURES: Array<[string, string]> = [
  ["Reliance Industries Limited", "reliance industries limited"],
  ["Zomato Ltd.",                   "zomato ltd"],
  ["A.B.C. & Co., PVT LTD",         "a b c co pvt ltd"],
  ["  Multiple   Spaces  ",         "multiple spaces"],
  ["Company#123",                   "company 123"],
  ["",                              ""],
  ["Antony Waste Ltd",              "antony waste ltd"],
  ["Antony Waste Limited",          "antony waste limited"],
  ["Kusumgar Ltd. O",               "kusumgar ltd o"],
  ["Tata\tConsultancy\nServices",   "tata consultancy services"],
  ["ONGC (India)",                  "ongc india"],
  ["HDFC\u00a0Bank",                "hdfc bank"], // NBSP treated as non-[a-z0-9 ] then collapsed
];

for (const [input, expected] of FIXTURES) {
  test(`normaliseName(${JSON.stringify(input)}) === ${JSON.stringify(expected)}`, () => {
    assert.equal(normaliseName(input), expected);
  });
}

test("normaliseName is idempotent (running twice yields the same result)", () => {
  for (const [input] of FIXTURES) {
    const once = normaliseName(input);
    assert.equal(normaliseName(once), once);
  }
});

test("normaliseName treats null / undefined as empty", () => {
  assert.equal(normaliseName(null as unknown as string), "");
  assert.equal(normaliseName(undefined as unknown as string), "");
});

test("twin variants collapse to distinct results (matches Guardrail B)", () => {
  // `Antony Waste Ltd` and `Antony Waste Limited` are BOTH normalised to
  // themselves under the raw normaliser; the twin-census check that catches
  // them lives in _scripts/check_data_contract.py, not in this normaliser.
  assert.notEqual(normaliseName("Antony Waste Ltd"), normaliseName("Antony Waste Limited"));
});

// ---------------------------------------------------------------------------
// Regenerating Python-side fixtures. Run in the repo root:
//
//   python3 -c "import re
//   def n(x): s=re.sub(r'[^a-z0-9 ]',' ',(x or '').lower()); return re.sub(r'\\s+',' ',s).strip()
//   for i in ['Reliance Industries Limited','Zomato Ltd.','A.B.C. & Co., PVT LTD','  Multiple   Spaces  ','Company#123','','Antony Waste Ltd','Antony Waste Limited','Kusumgar Ltd. O','Tata\\tConsultancy\\nServices','ONGC (India)','HDFC\\u00a0Bank']:
//       print(repr(i),'->',repr(n(i)))"
// ---------------------------------------------------------------------------
