"""Contract schema — GENERATED FROM PROD TRUTH (owner triage paste,
2026-07-17, information_schema column lists). The two core tables carry every
prod column; types are heuristic (NUMERIC/TEXT/DATE) which is sufficient for
column-existence + join contracts. Regenerate by rerunning
_scripts/triage_known_gaps.sql and updating the lists in the generator
(see git history of this file for the generator script).
"""

CONTRACT_DDL = """
DROP SCHEMA public CASCADE; CREATE SCHEMA public;
CREATE TABLE ipo_consolidated (
    company_name TEXT,
    nse_symbol TEXT,
    symbol TEXT,
    symbol_final TEXT,
    bse_code TEXT,
    isin TEXT,
    sector TEXT,
    industry TEXT,
    exchange TEXT,
    listing_exchange TEXT,
    is_sme BOOLEAN,
    ipo_status TEXT,
    ipo_open_date DATE,
    ipo_close_date DATE,
    listing_date DATE,
    issue_price NUMERIC,
    price_band_low NUMERIC,
    price_band_high NUMERIC,
    face_value NUMERIC,
    lot_size INT,
    issue_size_cr NUMERIC,
    fresh_issue_cr NUMERIC,
    ofs_cr NUMERIC,
    fresh_cr NUMERIC,
    sbi_rating TEXT,
    peer_ps NUMERIC,
    peer_name TEXT,
    fresh_issue_ratio NUMERIC,
    ofs_pct NUMERIC,
    issue_category TEXT,
    issue_type TEXT,
    pricing_method TEXT,
    greenshoe_price NUMERIC,
    promoter_holding_before NUMERIC,
    promoter_holding_after NUMERIC,
    promoter_dilution_pct NUMERIC,
    promoter_pledge_pct NUMERIC,
    pe_exit_flag BOOLEAN,
    revenue_cr NUMERIC,
    pat_cr NUMERIC,
    ebitda_cr NUMERIC,
    net_worth_cr NUMERIC,
    total_debt_cr NUMERIC,
    assets_cr NUMERIC,
    reserves_cr NUMERIC,
    revenue_cagr_3y NUMERIC,
    profit_cagr_3y NUMERIC,
    roe NUMERIC,
    roce NUMERIC,
    ronw_pct NUMERIC,
    pat_margin NUMERIC,
    ebitda_pct NUMERIC,
    debt_equity NUMERIC,
    eps_pre NUMERIC,
    eps_post NUMERIC,
    cash_flow_positive BOOLEAN,
    operating_cf_growth NUMERIC,
    period_ended TIMESTAMPTZ,
    ipo_pe NUMERIC,
    ipo_pe_pre NUMERIC,
    ipo_pe_post NUMERIC,
    ipo_pb NUMERIC,
    peer_median_pe NUMERIC,
    peer_pb NUMERIC,
    final_qib NUMERIC,
    final_qib_ex_anchor NUMERIC,
    final_anchor NUMERIC,
    final_nii NUMERIC,
    final_bnii NUMERIC,
    final_snii NUMERIC,
    final_retail NUMERIC,
    final_employee NUMERIC,
    final_total NUMERIC,
    nii_alloc_pct NUMERIC,
    qib_alloc_pct NUMERIC,
    retail_alloc_pct NUMERIC,
    structure_type TEXT,
    day1_qib NUMERIC,
    day1_nii NUMERIC,
    day1_retail NUMERIC,
    day2_qib NUMERIC,
    day2_nii NUMERIC,
    day2_retail NUMERIC,
    day3_qib NUMERIC,
    day3_nii NUMERIC,
    day3_retail NUMERIC,
    qib_backloaded BOOLEAN,
    hni_leverage_ratio NUMERIC,
    hni_breakeven_premium NUMERIC,
    gmp_value NUMERIC,
    gmp_pct NUMERIC,
    gmp_t10 NUMERIC,
    gmp_t7 NUMERIC,
    gmp_t5 NUMERIC,
    gmp_t3 NUMERIC,
    gmp_t1 NUMERIC,
    gmp_momentum TEXT,
    gmp_volatility NUMERIC,
    gmp_velocity NUMERIC,
    gmp_max_pct NUMERIC,
    gmp_min_pct NUMERIC,
    gmp_day_before_pct NUMERIC,
    gmp_peak_date DATE,
    gmp_breakdown_flag BOOLEAN,
    gmp_history TEXT,
    anchor_investors TEXT,
    anchor_names TEXT,
    anchor_quality TEXT,
    anchor_classification TEXT,
    anchor_total_cr NUMERIC,
    anchor_qib_alloc_cr NUMERIC,
    anchor_alloc_pct NUMERIC,
    anchor_domestic_pct NUMERIC,
    anchor_foreign_pct NUMERIC,
    anchor_top5_pct NUMERIC,
    anchor_count INT,
    anchor_tier1_count INT,
    anchor_flip_risk TEXT,
    anchor_lock30_date DATE,
    anchor_lock90_date DATE,
    anchor_lockup_30d_shares NUMERIC,
    anchor_lockup_90d_shares NUMERIC,
    brlm_names TEXT,
    brlm_tier TEXT,
    brlm_score NUMERIC,
    brlm_historical_win_rate NUMERIC,
    brlm_avg_listing_gain NUMERIC,
    brlm_pct_negative NUMERIC,
    registrar TEXT,
    market_makers TEXT,
    listing_price NUMERIC,
    listing_open NUMERIC,
    listing_high NUMERIC,
    listing_low NUMERIC,
    listing_close NUMERIC,
    listing_delivery_pct NUMERIC,
    listing_gap_pct NUMERIC,
    listing_vs_gmp_pct NUMERIC,
    listing_volume NUMERIC,
    above_vwap BOOLEAN,
    buy_qty NUMERIC,
    sell_qty NUMERIC,
    day1_liquid_float NUMERIC,
    float_turnover_ratio NUMERIC,
    hit_uc_day1 BOOLEAN,
    hit_lc_day1 BOOLEAN,
    hit_uc_day2 BOOLEAN,
    hit_lc_day2 BOOLEAN,
    ohlc_source TEXT,
    return_listing_open NUMERIC,
    return_current NUMERIC,
    return_open_5d NUMERIC,
    return_open_20d NUMERIC,
    max_upside_pct NUMERIC,
    max_upside_30d NUMERIC,
    max_drawdown_day1 NUMERIC,
    max_drawdown_day30 NUMERIC,
    nifty_alpha_day30 NUMERIC,
    days_to_break_issue INT,
    days_to_new_high INT,
    achieved_10pct BOOLEAN,
    nifty_at_listing NUMERIC,
    nifty_above_ema200 BOOLEAN,
    india_vix NUMERIC,
    listing_pcr NUMERIC,
    listing_regime TEXT,
    fii_monthly_flow_cr NUMERIC,
    dii_monthly_flow_cr NUMERIC,
    ipo_score INT,
    score_band TEXT,
    score_evidence TEXT,
    d10_best_pct NUMERIC,
    raw_score NUMERIC,
    lqi_base NUMERIC,
    lqi_final NUMERIC,
    regime_multiplier NUMERIC,
    archetype TEXT,
    operator_risk_flags TEXT,
    expected_return NUMERIC,
    prob_10pct_profit NUMERIC,
    prob_gain_10_20 NUMERIC,
    prob_gain_20_50 NUMERIC,
    prob_gain_gt50 NUMERIC,
    prob_loss_0_10 NUMERIC,
    prob_loss_gt10 NUMERIC,
    confidence_level TEXT,
    suggested_action TEXT,
    position_size NUMERIC,
    play_recommendation TEXT,
    play_confidence NUMERIC,
    play_stop_loss_pct NUMERIC,
    play_target_pct NUMERIC,
    play_hold_window TEXT,
    buy_at_open_score INT,
    vwap_entry_score INT,
    post30_score INT,
    anchor_expiry_score INT,
    risk_warning TEXT,
    key_reasons TEXT,
    similar_ipo_count INT,
    similar_ipos TEXT,
    chittorgarh_imported BOOLEAN,
    enrichment_status TEXT,
    data_source TEXT,
    is_backtest BOOLEAN,
    updated_at TIMESTAMPTZ,
    anchor_json JSONB,
    gmp_history_json JSONB,
    peer_json JSONB,
    financial_history_json JSONB,
    selling_shareholder_json JSONB,
    objects_json JSONB,
    risk_tags_json JSONB,
    promoter_json JSONB,
    market_snapshot_json JSONB,
    gap_bucket TEXT,
    is_profitable BOOLEAN,
    valuation_premium NUMERIC,
    regime_at_listing TEXT,
    tp1_exit_note TEXT,
    operator_lock_flag BOOLEAN,
    floor_price NUMERIC,
    ceiling_price NUMERIC,
    floor_defenses INT,
    level_verdict TEXT);
CREATE TABLE ipo_intelligence (
    id SERIAL PRIMARY KEY,
    symbol TEXT,
    company_name TEXT,
    sector TEXT,
    open_date DATE,
    close_date DATE,
    listing_date DATE,
    issue_price NUMERIC,
    price_band_low NUMERIC,
    price_band_high NUMERIC,
    listing_price NUMERIC,
    listing_open NUMERIC,
    issue_size_cr NUMERIC,
    fresh_issue_cr NUMERIC,
    ofs_cr NUMERIC,
    fresh_issue_ratio NUMERIC,
    qib_subscription_x NUMERIC,
    nii_subscription_x NUMERIC,
    rii_subscription_x NUMERIC,
    total_subscription_x NUMERIC,
    anchor_quality TEXT,
    anchor_domestic_pct NUMERIC,
    anchor_investors TEXT,
    ipo_pe NUMERIC,
    peer_median_pe NUMERIC,
    brlm_names TEXT,
    gmp_pct_t10 NUMERIC,
    gmp_pct_t7 NUMERIC,
    gmp_pct_t5 NUMERIC,
    gmp_pct_t3 NUMERIC,
    gmp_pct_t1 NUMERIC,
    gmp_momentum TEXT,
    gmp_volatility NUMERIC,
    nifty_at_listing NUMERIC,
    nifty_ema200 NUMERIC,
    nifty_above_ema200 BOOLEAN,
    score_retail_alloc NUMERIC,
    score_fresh_issue NUMERIC,
    score_qib_retail_ratio NUMERIC,
    score_anchor NUMERIC,
    score_qib_strength NUMERIC,
    score_valuation NUMERIC,
    score_brlm NUMERIC,
    score_gmp_current NUMERIC,
    score_gmp_momentum NUMERIC,
    score_gmp_volatility NUMERIC,
    score_nifty_regime NUMERIC,
    score_sector_heat NUMERIC,
    score_ipo_breadth NUMERIC,
    raw_score NUMERIC,
    lqi_base NUMERIC,
    regime_multiplier NUMERIC,
    lqi_final NUMERIC,
    archetype TEXT,
    return_listing_open NUMERIC,
    return_day1_close NUMERIC,
    return_day90 NUMERIC,
    return_cmp NUMERIC,
    max_drawdown_day30 NUMERIC,
    achieved_10pct BOOLEAN,
    prob_loss_gt10 NUMERIC,
    prob_10pct_profit NUMERIC,
    expected_return NUMERIC,
    confidence_level TEXT,
    similar_ipos TEXT,
    suggested_action TEXT,
    data_source TEXT,
    is_backtest BOOLEAN,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    ipo_score INT,
    ofs_pct NUMERIC,
    promoter_pre_equity NUMERIC,
    promoter_post_equity NUMERIC,
    promoter_dilution_pct NUMERIC,
    promoter_pledge_pct NUMERIC,
    pe_exit_flag BOOLEAN,
    anchor_lockup_30d_shares NUMERIC,
    anchor_lockup_90d_shares NUMERIC,
    gmp_velocity NUMERIC,
    gmp_breakdown_flag BOOLEAN,
    peer_pb NUMERIC,
    revenue_cagr_3y NUMERIC,
    profit_cagr_3y NUMERIC,
    debt_equity NUMERIC,
    anchor_total_cr NUMERIC,
    anchor_foreign_pct NUMERIC,
    anchor_top5_pct NUMERIC,
    anchor_flip_risk TEXT,
    anchor_stalwart_names TEXT,
    anchor_offshore_names TEXT,
    sector_3m_return NUMERIC,
    sector_6m_return NUMERIC,
    sector_rs_vs_nifty NUMERIC,
    sector_pe NUMERIC,
    sector_pb NUMERIC,
    peer_listing_average NUMERIC,
    india_vix NUMERIC,
    nifty_rs NUMERIC,
    fii_monthly_flow_cr NUMERIC,
    dii_monthly_flow_cr NUMERIC,
    listing_high NUMERIC,
    listing_low NUMERIC,
    listing_volume NUMERIC,
    listing_delivery_pct NUMERIC,
    listing_gap_pct NUMERIC,
    return_day7 NUMERIC,
    max_upside_pct NUMERIC,
    days_to_break_issue INT,
    days_to_new_high INT,
    gmp_value NUMERIC,
    gmp_percentage NUMERIC,
    qib_subscription NUMERIC,
    nii_subscription NUMERIC,
    retail_subscription NUMERIC,
    total_subscription NUMERIC,
    lot_size INT,
    ofs_percentage NUMERIC,
    promoter_holding_post NUMERIC,
    sector_pe_median NUMERIC,
    pe_ratio NUMERIC,
    revenue_growth_3yr NUMERIC,
    pat_growth_3yr NUMERIC,
    anchor_classification TEXT,
    enrichment_status TEXT,
    enriched_at TIMESTAMPTZ,
    kite_ipo_id TEXT,
    ipo_status TEXT,
    issue_open_date DATE,
    issue_close_date DATE,
    exchange TEXT,
    is_sme BOOLEAN,
    listing_exchange TEXT,
    kite_synced_at TIMESTAMPTZ,
    gmp_history TEXT,
    gmp_max_pct NUMERIC,
    gmp_min_pct NUMERIC,
    gmp_day_before_pct NUMERIC,
    gmp_peak_date DATE,
    listing_day_high NUMERIC,
    listing_day_low NUMERIC,
    listing_day_close NUMERIC,
    listing_volume_val NUMERIC,
    listing_vs_gmp_pct NUMERIC,
    hit_uc_day1 BOOLEAN,
    hit_lc_day1 BOOLEAN,
    anchor_count INT,
    anchor_names TEXT,
    anchor_tier1_count INT,
    anchor_lock30_date DATE,
    anchor_lock90_date DATE,
    brlm_score NUMERIC,
    brlm_avg_listing_gain NUMERIC,
    brlm_pct_negative NUMERIC,
    return_day1_open NUMERIC,
    return_day180 NUMERIC,
    return_day365 NUMERIC,
    max_upside_30d NUMERIC,
    max_drawdown_30d NUMERIC,
    operator_risk_flags TEXT,
    listing_vix_val NUMERIC,
    listing_pcr NUMERIC,
    listing_regime TEXT,
    play_recommendation TEXT,
    play_confidence NUMERIC,
    play_reasons TEXT,
    play_stop_loss_pct NUMERIC,
    play_target_pct NUMERIC,
    play_hold_window TEXT,
    play_updated_at TIMESTAMPTZ,
    chittorgarh_imported BOOLEAN,
    nse_symbol TEXT,
    bse_code TEXT,
    isin TEXT,
    listing_close_price NUMERIC,
    return_current NUMERIC,
    anchor_investment_cr NUMERIC,
    anchor_alloc_pct NUMERIC,
    roe NUMERIC,
    roce NUMERIC,
    pat_margin NUMERIC,
    ebitda_pct NUMERIC,
    ipo_pb NUMERIC,
    eps_pre NUMERIC,
    eps_post NUMERIC,
    ipo_pe_pre NUMERIC,
    ipo_pe_post NUMERIC,
    revenue_cr NUMERIC,
    pat_cr NUMERIC,
    ebitda_cr NUMERIC,
    net_worth_cr NUMERIC,
    total_debt_cr NUMERIC,
    anchor_qib_alloc_cr NUMERIC,
    hold_7_days BOOLEAN,
    exit_eod BOOLEAN,
    gain_open_close NUMERIC,
    gain_open_high NUMERIC,
    return_open_5d NUMERIC,
    return_open_20d NUMERIC,
    ohlc_source TEXT,
    sbi_rating TEXT,
    fresh_cr NUMERIC,
    peer_ps NUMERIC,
    peer_name TEXT,
    chittorgarh_slug TEXT,
    score_band TEXT,
    score_evidence TEXT,
    d10_best_pct NUMERIC,
    listing_cir NUMERIC,
    cir_3d_avg NUMERIC,
    anchor_pct_issue NUMERIC,
    registrar TEXT,
    rii_subscription NUMERIC,
    listing_close NUMERIC,
    mcap_offer NUMERIC,
    quality_score INT,
    quality_conf INT,
    eps_source TEXT,
    score_expected_win NUMERIC,
    score_expected_med NUMERIC);
CREATE TABLE ipo_verdicts (company_name TEXT, verdict TEXT, why_trade TEXT,
    why_caution TEXT, why_avoid TEXT, why_passes TEXT, regime TEXT,
    quality_promoter BOOLEAN, ai_summary TEXT, score NUMERIC, confidence NUMERIC,
    sub_scores JSONB, computed_at TIMESTAMPTZ);
CREATE TABLE ipo_flags (company_name TEXT, red_flags TEXT[], green_checks TEXT[],
    red_count INT, green_count INT, computed_at TIMESTAMPTZ);
CREATE TABLE ipo_broker_consensus (company TEXT, consensus TEXT, n_brokers INT,
    consensus_score NUMERIC);
CREATE TABLE ipo_rhp_intel (company_name TEXT, verdict TEXT, one_line TEXT,
    quality_gate TEXT, margin_of_safety NUMERIC, full_json JSONB, confidence TEXT,
    rhp_url TEXT, pdf_sha256 TEXT);
CREATE TABLE ipo_research_notes (source TEXT, company TEXT, nse_symbol TEXT,
    rating TEXT, full_json JSONB, one_line TEXT, peer_name TEXT, pdf_path TEXT,
    peer_ps NUMERIC, note_ps NUMERIC, parsed_at TIMESTAMPTZ, price_low NUMERIC,
    price_high NUMERIC, fresh_cr NUMERIC, ofs_cr NUMERIC, issue_size_cr NUMERIC,
    qib_pct NUMERIC, nii_pct NUMERIC, retail_pct NUMERIC, brlms TEXT,
    registrar TEXT, loss_making BOOLEAN);
CREATE TABLE price_candles (symbol TEXT, date DATE, open NUMERIC, low NUMERIC,
    high NUMERIC, close NUMERIC, volume BIGINT);
CREATE TABLE ipo_tick_feed (symbol TEXT, ltp NUMERIC, vwap NUMERIC,
    vwap_dist NUMERIC, obir NUMERIC, day_volume BIGINT, momentum TEXT,
    divergence TEXT, signal TEXT, recorded_at TIMESTAMPTZ);
CREATE TABLE ipo_level_analysis (symbol TEXT, trade_date DATE, issue_price NUMERIC,
    listing_open NUMERIC, gap_pct NUMERIC, gap_bucket TEXT, floor_price NUMERIC,
    ceiling_price NUMERIC, floor_defenses INT, poc_price NUMERIC, verdict TEXT,
    risk_note TEXT, circuit_locked BOOLEAN, session_vwap NUMERIC,
    day_high NUMERIC, day_low NUMERIC, day_close NUMERIC, close_vs_vwap NUMERIC,
    floor_volume BIGINT, ceiling_volume BIGINT, obir_open NUMERIC,
    obir_close NUMERIC, profile_json JSONB, tick_count INT,
    computed_at TIMESTAMPTZ);
CREATE TABLE market_regimes (evaluation_date DATE, active_regime TEXT,
    india_vix NUMERIC);
-- prod-confirmed tables (triage rows 1-5) --
CREATE TABLE job_runs (id BIGSERIAL PRIMARY KEY, job TEXT, status TEXT,
    requested_by TEXT, requested_at TIMESTAMPTZ, started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ, exit_code INT, error TEXT, log_tail TEXT);
CREATE TABLE kite_session (id SERIAL, user_id TEXT, access_token TEXT,
    api_key TEXT, created_at TIMESTAMPTZ, expires_at TIMESTAMPTZ, status TEXT);
CREATE TABLE market_snapshot (id SERIAL, nifty_price NUMERIC, nifty_chg_pct NUMERIC,
    nifty_vs_ema200 NUMERIC, banknifty_price NUMERIC, banknifty_chg_pct NUMERIC,
    vix NUMERIC, pcr NUMERIC, fii_flow NUMERIC, dii_flow NUMERIC,
    advance_decline_ratio NUMERIC, sgx_nifty NUMERIC, dow_fut NUMERIC,
    nifty_vs_20dma NUMERIC, nifty_vs_50dma NUMERIC, nifty_vs_200dma NUMERIC,
    market_regime TEXT, market_risk_score NUMERIC, market_opportunity_score NUMERIC,
    recommended_exposure NUMERIC, sector_data_json JSONB, confidence TEXT, notes TEXT,
    last_updated TIMESTAMPTZ, captured_at TIMESTAMPTZ);
CREATE TABLE platform_config (key TEXT PRIMARY KEY, value TEXT,
    updated_at TIMESTAMPTZ);
CREATE TABLE rhp_run_log (id SERIAL, company TEXT, spent_usd NUMERIC, ok BOOLEAN,
    note TEXT, ran_at TIMESTAMPTZ);
-- route-self-created tables — DDL VERBATIM from the routes (authoritative) --
CREATE TABLE ipo_gmp (id SERIAL PRIMARY KEY, ipo_name TEXT NOT NULL,
    gmp_price NUMERIC NOT NULL, gmp_pct NUMERIC, recorded_at TIMESTAMPTZ);
CREATE TABLE ipo_preopen_book (id SERIAL PRIMARY KEY, symbol TEXT,
    discovery_price NUMERIC, buy_qty BIGINT, sell_qty BIGINT, lean_pct NUMERIC,
    captured_at TIMESTAMPTZ, source TEXT, state_hash TEXT, ieq BIGINT,
    payload JSONB);
CREATE TABLE access_requests (email TEXT PRIMARY KEY, name TEXT, status TEXT,
    requested_at TIMESTAMPTZ, decided_at TIMESTAMPTZ, decided_by TEXT);
CREATE TABLE allowed_users (email TEXT PRIMARY KEY, added_by TEXT,
    added_at TIMESTAMPTZ);
CREATE TABLE distraction_log (id BIGSERIAL PRIMARY KEY, owner_email TEXT,
    who TEXT, severity TEXT, what TEXT, minutes INTEGER, created_at TIMESTAMPTZ);
CREATE TABLE subscription_history (id SERIAL PRIMARY KEY, ipo_name TEXT,
    day INTEGER, qib_x NUMERIC, nii_x NUMERIC, retail_x NUMERIC, total_x NUMERIC,
    notes TEXT, recorded_at TIMESTAMPTZ, UNIQUE(ipo_name, day));
CREATE TABLE user_settings (key TEXT PRIMARY KEY, value JSONB,
    updated_at TIMESTAMPTZ);
-- prod tables from SCHEMA.md inventory referenced by routes --
CREATE TABLE ipo_daily_levels (symbol TEXT, date DATE, t INT, close NUMERIC,
    floor NUMERIC, ceiling NUMERIC, poc NUMERIC, cushion NUMERIC,
    broke_floor BOOLEAN, broke_ceiling BOOLEAN);
CREATE TABLE delivery_data (symbol TEXT, date DATE, delivery_percentage NUMERIC,
    delivery_quantity BIGINT);
CREATE TABLE stock_fundamentals (symbol TEXT, nse_symbol TEXT, name TEXT,
    company_name TEXT, industry TEXT, pe NUMERIC, pb NUMERIC, roe NUMERIC,
    market_cap NUMERIC, market_cap_cr NUMERIC, current_price NUMERIC,
    business_dna_score NUMERIC, business_dna_grade TEXT, earnings_score NUMERIC,
    smart_money_score NUMERIC, smart_money_signal TEXT,
    sector_rotation_score NUMERIC, return_3m NUMERIC, return_6m NUMERIC);
CREATE TABLE company_master (symbol TEXT, nse_symbol TEXT, name TEXT,
    company_name TEXT, isin TEXT, industry TEXT, market_cap NUMERIC,
    market_cap_cr NUMERIC);
CREATE TABLE technical_signals (symbol TEXT, signal TEXT, signal_date DATE,
    strength NUMERIC, computed_at TIMESTAMPTZ, updated_at TIMESTAMPTZ);
CREATE TABLE management_commentary (symbol TEXT, quarter TEXT, summary TEXT,
    sentiment NUMERIC, scored_at TIMESTAMPTZ);
CREATE TABLE pipeline_steps (id SERIAL, run_date DATE, step TEXT, script TEXT,
    ok BOOLEAN, error TEXT, ran_at TIMESTAMPTZ);
CREATE TABLE pipeline_failures (id SERIAL, step TEXT, script TEXT,
    stderr_tail TEXT, failed_at TIMESTAMPTZ);
"""
